import Config from "react-native-config";

export const BASE_PROJECT_API_URL = Config.BASE_PROJECT_API_URL
export const BASE_PROJECT_AUTH0_DOMAIN = Config.BASE_PROJECT_AUTH0_DOMAIN
export const BASE_PROJECT_AUTH0_CLIENT_ID = Config.BASE_PROJECT_AUTH0_CLIENT_ID
export const BASE_PROJECT_AUTH0_AUDIENCE = Config.BASE_PROJECT_AUTH0_AUDIENCE